# Generated by Django 5.2.8 on 2025-11-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('productName', models.CharField(max_length=30)),
                ('productID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=400)),
                ('stock', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
